version: '2'

services:
  app:
    image: 'network:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: "app"
    depends_on:
      [ tarantool ]
    environment:
      - TARANTOOL_NODES=tarantool:3301
      - TARANTOOL_USERNAME=tarantool
      - TARANTOOL_PASSWORD=tarantool
  tarantool:
    container_name: tarantool
    image: tarantool/tarantool:1.7
    command: tarantool /usr/local/share/tarantool/app.lua
    environment:
      - TARANTOOL_USER_NAME=tarantool
      - TARANTOOL_USER_PASSWORD=tarantool
    ports:
      - 3301:3301
    volumes:
      - ./app.lua:/usr/local/share/tarantool/app.lua